### ISSUE TITLE
 if (_namePrefix != null) should be if (!TextUtils.isEmpty(_namePrefix))

### ISSUE THREAD

**Issue by helloyingying** [SalomonBrys/ANR-WatchDog#17]
if (_namePrefix != null) should be if (!TextUtils.isEmpty(_namePrefix)) .
Because if I ignore setting the only main Thread, `error = ANRError.New(_namePrefix, _logThreadsWithoutStackTrace)` will be executed, but it is not efficient.
```
           // If the main thread has not handled _ticker, it is blocked. ANR. 
            if (_tick == lastTick) {
                ANRError error;
                if (_namePrefix != null)
                    error = ANRError.New(_namePrefix, _logThreadsWithoutStackTrace);
                else 
                    error = ANRError.NewMainOnly();
                _anrListener.onAppNotResponding(error);
                return ; 
            } 
```

**Comment by SalomonBrys** [comment]
Nope.
If `_namePrefix` is:

 - Not null and empty (default) = it will report all threads
 - Not null and not empty = it will report main thread + any thread that starts with it
 - Null = it will report only the main thread

So, this is by design ;)

As for the efficiency, this code only runs when an ANR is detected, which makes efficiency useless :p .
