### ISSUE TITLE
Caught Exceptions having error object from ANRWatchDog not getting logged on Crashlytics Dashboard

### ISSUE THREAD

**Issue by harminderkharbanda** [SalomonBrys/ANR-WatchDog#29]
Hi,

I am using ANRWatchDog to catch ANRs. It provides an 'error' object which I am logging to crashlytics. I am getting report upload complete logs for crashlytics but nothing appears on dashboard. Crashlytics is working fine at the same time for other types of caught/uncaught exceptions.

private ANRListener listener = new ANRListener() {
        @Override
        public void onAppNotResponding(ANRError error) {
            try{
                Crashlytics.logException(error);
           
            } catch (Exception e) {
                Logger.e(TAG, "Exception while sending ANR stacktrace to Crash reporter "+e.getStackTrace());
            }

        }
    };

I have raised the issue with Crashlytics team as well. Wanted to know here if any known issue exists in ANRWatchDog.

**Comment by voidshad** [comment]
Hi,
We`ve come across exactly the same problem. onAppNotResponding callback is raised, but the issue on crashlytics never created. Any thoughts or updates on this?

**Comment by navaneet** [comment]
I too was having this issue earlier, it seems when you Log a non runtime exception in crashlytics it creates nonfatal exceptions in fabric dashboard since ANRs don't necessarily crash an application. You need to toggle the switch in the fabric dashboard to show all exceptions as by default it only shows fatal exceptions. Hope it helps!

**Comment by harminderkharbanda** [comment]
@navaneet Regarding the dashboard thing, I have already selected "All Events".

Will surely look into the 2nd part of your solution though. Thanks!

Btw Fabric team replied that they are receiving an empty report and hence it is not showing in the dashboard. Any thoughts?

**Comment by navaneet** [comment]
Not sure, however if it logs into logcat it should log into fabric too.

**Comment by voidshad** [comment]
I don`t think that proguard is the case because we`ve got the same situation for our debug builds (which aren`t minimized). But I`ll give it a try. 
I also tried it with some dummy exception and it works fine. So the problem is definitely with ANRError class

**Comment by mflesh1** [comment]
I have been looking into this, and I was able to get this to work by setting the ANRWatchDog to only report the main thread.

`anrWatchDog.setReportMainThreadOnly()`

I still cannot get this to work without that setting.

**Comment by mflesh1** [comment]
I contacted Crashlytics support and they stated:

`Our limit is around 64kb or 128kb in some cases. It looks like ANRwatchdog is producing reports over 500kb`

So looks like currently you must use the setReportMainThreadOnly() option as it limits the size of the report.

**Comment by umair6** [comment]
@mflesh1  I think issue is because of ANR format. Crashlytics is expecting an exception which normally contains a message and a stack trace. When "setReportMainThreadOnly"  is disabled, ANRError creates a nested stack trace of all threads which Crashlytics does not accept. If I convert the ANRError into a string, as suggested by @navaneet , then it get posted fine. But then there is error grouping issue on crashlytics dashboard which I am currently trying to figure out. .

**Comment by SalomonBrys** [comment]
The documentation warns about this.
That's all I can do :disappointed:
