### ISSUE TITLE
How to be sure if main thread is blocked or not?

### ISSUE THREAD

**Issue by PanWangJ** [SalomonBrys/ANR-WatchDog#6]
Hi, I've found your project with how to detect ANR in Android and I found it very useful, thanks a lot. But there is a port that I don't quite understand that how do you be sure if main thread is blocked? 
Your code:

    public void run() {
        setName("|ANR-WatchDog|");

        int lastTick;
        while (!isInterrupted()) {
            lastTick = _tick;
            _uiHandler.post(_ticker);
            try {
                Thread.sleep(_timeoutInterval);
            }
            catch (InterruptedException e) {
                _interruptionListener.onInterrupted(e);
                return ;
            }

            // If the main thread has not handled _ticker, it is blocked. ANR.
            if (_tick == lastTick) {
                ANRError error;
                if (_namePrefix != null)
                    error = ANRError.New(_namePrefix, _logThreadsWithoutStackTrace);
                else
                    error = ANRError.NewMainOnly();
                _anrListener.onAppNotResponding(error);
                return ;
            }
        }
    }
The value of current **_tick** is passed to **lastTick** before Runnable **_ticker** is passed to main thread. Let's assume **_tick** is 0 which means **lastTick** is 0 as well. Then the watchDog thread is gonna sleep for 5s without interruption. Then the code check if the new **_tick**  equals **lastTick**:

    if (_tick == lastTick)
By that I saw that if the new value of **_tick** equals the value of **lastTick** then we know the thread is blocked. This is the part I just don't understand, isn't it possible that the new value of **_tick** is 0 since its value will be set between 0~9 **(_tick = (_tick + 1) % 10)**??? Is there anything wrong about my analysis about this? I knew that it has to be something wrong with myself but I just can't find out, hope somebody can help me, thanks a lot!

**Comment by SalomonBrys** [comment]
I think you misunderstood `_tick = (_tick + 1) % 10)`.
It means that **_tick** will be incremented by ***one*** and then set to the **result modulo ten**.

So, before `_uiHandler.post(_ticker)`, we know that **_tick == lastTick**, then the **_ticker** task will increment **_tick** by one and ensure that it remains within **[0-10[**.

- When **lastTick** is 0, then **_ticker** will *(try to)* set **_tick** to 1.
- When **lastTick** is 1, then **_ticker** will *(try to)* set **_tick** to 2.
- ...
- When **lastTick** is 9, then **_ticker** will *(try to)* set **_tick** to 0.

So, as the **_ticker** task is only run once between `lastTick = _tick` and `if (_tick == lastTick)`, **_tick** can not be the same as **lastTick** after one **_ticker** execution.

The modulo 10 is because, you know, we have 10 fingers. Any modulo would have done. In truth, the actual best meaningful modulo would have been `(Integer.MAX_VALUE - 1)`.

I did this to avoid overflow.
Granted, to overflow, with **_timeoutInterval** set to 5 seconds, the app would have to remain opened 340 years...

...I hope future generation will remember me fondly ;)

**Comment by PanWangJ** [comment]
Ah, the problem of me is not with the **_tick = (_tick + 1) % 10**, but actually what I got wrong is with the Runnable object **_ticker**. I thought that this Runnable object will keep running in the main thread and thus change the value of **_tick** from 0 to 9 continuously. Anyway, thanks for your explanation, I believe this is a stupid mistake that I will bear in mind for quite a long time. 
Thanks again!

**Comment by PanWangJ** [comment]
And, you are really funny about the 340 years thing :)
